[root]
depends_on = ["service", "install"]

[[modules]]
paths = ["git_ops", "service"]
depends_on = []

[[modules]]
path = "install"
depends_on = ["service", "//tach.hooks"]

[[interfaces]]
expose = ["get_changed_files", "get_current_branch_info"]
from = ["git_ops"]

[[interfaces]]
expose = ["install_pre_commit"]
from = ["install"]
