class TachError(Exception): ...


class TachParseError(TachError): ...


class TachSetupError(TachError): ...


class TachInitError(TachError): ...


__all__ = ["TachError", "TachParseError", "TachSetupError", "TachInitError"]
